src/modules/sym.txt
This PR implements Proposal 4 (iteration 1) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds two `divides` variants: `divides.not.rev`, and `divides.struck`.
=> Add missing `divides` variants (Proposal 4)

src/modules/sym.txt
This PR implements Proposal 3 (iteration 3) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds an `interleave` symbol and two variants.
=> Add interleave symbol and variants (Proposal 3)

src/modules/sym.txt
This PR implements Proposal 2 (iteration 1) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds die face symbols as `die.{one,two,three,four,five,six}`, with `die.six` being the default.
=> Add die face symbols (Proposal 2)

src/lib.rs
This is a bit of a 'how did we not catch this earlier?' story, but in all fairness this repository is only 5 days old.
I was checking out the Rust API when I noticed `ROOT.get("sym")` returned `None`—after which I came to realise `ROOT`'s members weren't sorted in key-order, meaning the `binary_search_by_key` call didn't uphold its preconditions :P
I simply swapped the order of `SYM` and `EMOJI` in `ROOT`'s definition and added a test to ensure all modules remain sorted indefinitely.
@laurmaedje I do think this fix warrants a new release to crates.io, this was a slightly major bug.
=> Sort members of `codex::ROOT`

src/modules/sym.txt
This PR implements Proposal 19 (~iteration 1~ iteration 2) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It removes compatibility codepoints. For some context, see [the Unit Symbols paragraphs of section 22.2.1 of the Unicode 16.0.0 Core Specification](https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-22/#G20445), as well as the description of Proposal 19 in the aforementioned Symbol Proposals document (copied below for simplicity).
`angle.l.double` and `angle.r.double` change codepoints. `degree.c`, `degree.f`, `ohm`, `ohm.inv`, `angstrom`, and `kelvin` become invalid.
=> Remove compatibility symbols (Proposal 19)

src/modules/sym.txt
This PR implements Proposal 12 (iteration 3) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds a new `errorbar` symbol with multiple variants.
=> Add error bar symbols (Proposal 12)

src/modules/sym.txt
This PR adds the symbols from Proposal 8 (iteration 1) from the [Symbols Proposal Document](https://typst.app/project/pHN_iIPjeuCyI_N2JZB84o).
I changed the name from `colon.triple` to `colon.tri` to avoid making it seem related to `colon.double` (which is ∷)
It's also closer to the unicode name (Tricolon).
=> Add tricolon symbols (Proposal 8)

src/modules/sym.txt
This PR implements Proposal 24 (iteration 2) from the [Symbol Proposals Document](https://typst.app/project/pHN_iIPjeuCyI_N2JZB84o).
I also added `to` as per our [Discussion on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1331253538331951115).
This is a draft since it would be better done with the tools from #27.
=> Add `to` and `mapsto` (Proposal 24)

build.rs, src/lib.rs
This PR adds the ability to deprecate definitions (i.e., symbols and modules), as suggested in https://github.com/typst/codex/pull/2#issuecomment-2501943047.
Syntax-wise, marking a definition as deprecated can be done by adding <code>@deprecated: <i>deprecation message</i></code> to the line preceding the definition.
Currently, this feature is not used, but it could be used to mark  `sym.inter` as deprecated in #17.[^1]
[^1]: Proposal 14 (partially implemented in #17) also removes the `sym.integral.sect` variant, which, as a variant, cannot be deprecated with this PR. This is probably fine in this specific case, because `sym.integral.sect` is not a highly used symbol, but we may want the ability to deprecate specific variants in the future.
Deprecated definitions have an associated …
=> Make it possible to deprecate symbols and modules

src/modules/sym.txt
The `diff` symbol was removed by https://github.com/typst/typst/pull/5388. What I didn't realize when merging this, is not just that there was no deprecation warning (which was obvious), but that the 0.11.0 changelog said "`diff` will be deprecated in the future". So it wasn't even deprecated at all.
There was also some heated discussion on Discord about `diff` recently, so maybe we should discuss it again before proceeding with the planned deprecation.
=> Bring back `diff`

src/modules/sym.txt
This PR implements the first part of Proposal 14 (iteration 1) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds `inter` as an alternative for `sect`. Eventually, `sect` should be deprecated, and later removed. For more context, see [the discussion on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1311370099382292520).
For now, there is no infrastructure to deprecate symbols in Codex, nor is there a way to deprecate a constant in Typst. This makes it impossible to deprecate `sect` immediately. However, since `sect` is a commonly used symbol, I believe the sooner we introduce its new name, the better.
Since this PR assumes the future removal of a symbol (`sect`) and a variant (`integral.sect`), and even though …
=> Add `inter` as an alternative for `sect` (Proposal 14, part I)

src/modules/sym.txt
#14 removed `sym.angstrom` because it used a deprecated codepoint. However, multiple people use this symbol and would have no way of inputting it easily with most keyboards. This PR adds back `sym.angstrom`, except is uses U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE, which is the one that should be used in place of the deprecated U+212B ANGSTROM SIGN.
This follows [a discussion on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1336610042685820929).
=> Add `angstrom` back (with a non-deprecated codepoint)

src/modules/sym.txt
This PR adds struck arrows, as well as twohead tailed arrows.
For singly struck arrows, I chose the `.struck` modifier, which is consistent with its use in `parallel.struck` in contrast to `parallel.not`. Unicode also defines doubly struck arrows. For those, an additional modifier needs to be created, and i am unsure of the name to use. Maybe `.doublestruck`, or `.dstruck`? I marked the PR as a draft for this reason.
=> Add struck arrows

src/modules/sym.txt
This PR implements Proposal 26 (iteration 1) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It changes `planck` to ħ (which gets italicized to ℏ in math thanks to https://github.com/typst/typst/pull/5492), and removes the `planck.reduce` variant. For more context, see [the discussion on Discord](https://discord.com/channels/1054443721975922748/1277628305142452306/1325065616444624956).
There is no way to take advantage of the symbol deprecation mechanism introduced in #19 to make this change smoother.
`planck.reduce` becomes invalid, and `planck` changes codepoint.
=> Make `planck` more useful (Proposal 26)

CHANGELOG.md
=> Mention that `ohm` was removed in the 0.1.0 changelog

src/modules/sym.txt
`diff` was meant to be deprecated since the addition of `partial` in https://github.com/typst/typst/pull/3211. This was indicated in the [Typst 0.11.0 changelog](https://typst.app/docs/changelog/0.11.0/#symbols).
=> Deprecate `diff`

src/modules/sym.txt
The `¢` "cent" symbol is used when referring to fractional dollars in US currency. The `₵` "cedi" (Ghanaian Cedi) is the legal tender of the Republic of Ghana.
=> Add U+00A2 `¢` and U+20B5 `₵`

src/modules/sym.txt
adds U+2322 `⌢` (frown) and U+2323 `⌣` (smile). they are used in certain cohomology theories for cap and cup products. in latex, they are represented by `\frown` and `\smile`.
=> Add U+2322 and U+2323

src/modules/emoji.txt, src/modules/sym.txt
This PR implements Proposal 1 (iteration ~2~ 3) from the [Symbol Proposals document](https://typst.app/project/riXtMSim5zLCo7DWngIFbT). It adds gender symbols under a new `sym.gender` sub-module, ~and removes the old `emoji.transgender` symbol~.
~`emoji.transgender` is no longer valid.~ No breaking change as of iteration 3 (07bfd3134a695a990e9fd197be909fd7db28de0e).
=> Add gender symbols (Proposal 1)

src/modules/sym.txt
Remove the `small` variants of `ast`, `plus`, `eq`, `gt` and `lt`.
These are compatibility symbols for Chinese in the [Small Form Variants](https://en.wikipedia.org/wiki/Small_Form_Variants) block, and should not have been added in the first place.
=> Remove chinese compatibility characters

src/modules/sym.txt
We were missing the most important unicode symbol.
Context: https://en.wikipedia.org/wiki/Angzarr
=> Add angzarr

src/modules/sym.txt
We had two alternate spellings largely because there was no mechanism for deprecation at the time. I'm not opposed to maintaining more than one name for a symbol if they're fundamentally different and there's a good reason for it, but different romanizations is many steps too far in my opinion. A similar example came up recently for the Mongolian currency, which you can find references to as tugrik, tughrik, tugrug, togrog, tögrög, and I'm sure even more.
1. The spellings alef, bet, gimmel and dalet are, as far as I can tell, closer to modern hebrew romanization (actually, "gimmel" seems to be very obscure regardless). However, aleph, beth, gimel and daleth are almost universal in an academic setting, which is where these symbols are intended for.
A search for "alef" on arxiv brings up …
=> Deprecate alternate spellings of hebrew characters

src/modules/sym.txt
This adds the name `slash.circle` for the Unicode symbol ⊘, which was inexplicably missing despite seemingly every other circled operator being included. This symbol is sometimes used for Hadamard (element-wise) division, and is available as `\oslash` in LaTeX.
=> Add `slash.circle`

src/modules/sym.txt
The current name was inconsistent with our naming scheme.
There's also a broader discussion to be had whether all the `.rev` variants we have make sense. If there is a "canonical" direction, such as for `in`, then yes, but I have no idea what to expect for `angle.spheric`. It would better to use names like `angle.spheric.r`, `angle.spheric.l` and `angle.spheric.t` to indicate which way it opens.
I didn't make that change, but the same comment applies to `angle.rev`, `angle.right.rev`, and `angle.arc.rev`
=> Rename angle.spheric.top to angle.spheric.t

src/modules/sym.txt
Adds various astronomical symbols. These days, I believe only the symbols for the sun, earth and jupiter are commonly used in actual science, but do see use in astrology.
There's also
- ♇ for Pluto, but I skipped that one since it's no longer a planet.
- A bunch of moon symbols, some which can act as emojis
=> Add astronomical symbols

src/modules/sym.txt
This is an archaic greek letter, but it does see use (though rarely), and appears in reasonably complete math fonts. It's also the only one that gets a name in unicode-math (the latex package).
Other archaic symbols exist, but I don't think there is a point in adding them unless requested.
=> Add digamma

Cargo.toml, src/lib.rs, src/styling.rs
This PR adds functions and the related infrastructure needed to take a character/string and a style in math (e.g. blackboard-bold, monospace), and return it in styled form. It is implemented under the feature `styling`, which I've added as a default.
Moving this to Codex was brought up briefly on Discord, and whilst it doesn't directly fall under "naming Unicode symbols", I think it still fits quite nicely in this crate. I may have jumped the gun a little on this, but it wasn't much work to do. Hopefully this PR starts some more thorough discussion of this idea. I also think that moving this outside of the main typst repo will be an improvement and make it more maintainable.
=> Add math styling module

build.rs, src/lib.rs, src/modules/sym.txt
This just changes all instances of `char` to `&str`/`String`.
Some notes:
- Allocating every variant in `build.rs` was the easiest way to do it. I'd have at least two other ideas about how to reduce allocations, but both require a bit more code complexity, so idk if it'd be worth it.
- The way the multi-character syntax interacts with `U+XXXX` escapes is by just treating each `U+` as the start of one and always taking the maximal hex value following that. I think this is fine, since we don't have any symbols or variants whose values contain hex digits anyway.
Future work would be updating `sym.txt` and `emoji.txt` to resolve #25. For that, I'd like to extend the syntax with suffixes `!text` and `!emoji` that get converted to `U+FE0E` and `U+FE0F`, so that it's less cryptic. Not sure if …
=> Allow multi-character symbols/variants

src/lib.rs, src/modules/sym.txt
This is in conflict with https://github.com/typst/codex/issues/34 . However, circled symbols are _extremely_ common, both in terms of the number of characters (we're still missing a bunch of symbols) and in usage. Therefore, I believe that it deserves its own short and cute modifier, which also has the benefit of resolving the ambiguous conflicting uses of "circle". There is also precedence, in the form of "oo" to mean infinity.
Notes:
- ast.circle was really a circled variant of ast.op, so I used ast.op.o.
- circle.nested was really a circled variant of circle.stroked.tiny, so I used circle.stroked.tiny.o
- The aliases compose.o and convolve.o were missing. I added them
I initially wanted to add additional symbols in this PR, but in the process of looking into this I discovered a number …
=> Rename circle modifier for symbols that are circled to "o"

src/modules/sym.txt
There are also some additional dingbats, but I avoided adding them both because naming is hard, they double as emojis, and it's not entirely clear whether they belong under bullet or not.
Closes #88
=> Add bullets

src/modules/sym.txt
To my knowledge, these are the remaining circled mathematical operators in unicode.
There are a multitude more symbols in other categories, plus a generic composing circle (https://www.compart.com/en/unicode/U+20DD), but it seems natural to leave those for the future.
- Curiously, while there is a circled slanted division sign, there is no non-circled one.
- I debated whether I should add `.half` to `plus.o.l` etc, but ended up not doing that. The choice here is the same as in @MDLC01 's document.
- I think `times.o.o` would be a better name than `times.o.double`, but this is impossible right now.
=> Additional circled mathematical symbols

src/modules/sym.txt
⦝ is specifically ⊾ with a dot, and `.sq` should mean a "squarified" version of a symbol (as opposed to `.square`)
Alternatively we could rename `angle.right.sq` to `angle.right.square` instead, but that would be a breaking change.
=> Add missing arc modifier to `angle.right.dot`, rename `angle.right.sq`

src/modules/sym.txt
Currently, we had two entirely different families of symbols under `angle`. Namely all the angle brackets, and the geometry kind. I've renamed the brackets to chevron, which is an alternate name for them that someone suggested. At the same time, I moved the remaining angles to the "Geometry" section.
For consistency, I also renamed `quote.angle` to `quote.chevron`.
=> Rename angle brackets and quotes to chevron

src/modules/sym.txt
Context: There are in essence four different types of double delimiters
1. "True" double delimiters, where the symbol is repeated twice
Based on naming conventions , these should get the `.double` modifier. I don't think this point is controversial.
2. A single delimiter closed with a vertical line (Comes from "Z-notation")
I called these `.bar` in the previous iteration, but used `.closed` here (following @MDLC01 's suggestion ). I'm not entirely happy with either name.
3. Black / filled delimiters.
There is only one pair of these, namely the tortoise shells ⦗ and ⦘. These don't show up correctly here, but here is what they look like in Noto Sans Math and Stix Two Math:
(They are completely broken in New Computer Modern Math)
The natural name is `.filled`
4. White / double-struck / …
=> Add various flavors of double delimiters

src/modules/sym.txt
While oblique can apparently be used to refer to any angle that's not right, that's clearly not the intended meaning here. This is specifically an obtuse angle (that is, larger than 90 degrees).
=> `angle.oblique` should be `angle.obtuse`

src/modules/sym.txt
For instance, the `paren.l.double` can also trigger from just `paren.double` and even `paren.double.r` (because it goes through the intermediate `paren.double`), so the more generic message is more helpful.
In Typst, this now gives the following output (together with the new deduplication strategy discussed in Discord):
```
warning: `ast.small` is deprecated (CJK compatibility character), use ﹡ or `\u{fe61}` instead
┌─ hi.typ:2:24
│
2 │ $ bracket.stroked.l ast.small bracket.double.r $
│                         ^^^^^
warning: `bracket.double` is deprecated, use `bracket.stroked` instead
┌─ hi.typ:2:38
│
2 │ $ bracket.stroked.l ast.small bracket.double.r $
│                                       ^^^^^^
```
I've opted to only apply this change when the modifier is sensible without the other …
=> Make some deprecation warnings more generic
